<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'instanweb.module.nhbusinesscentral.businesscentralconfiguration.config.data.handler' shared service.

return $this->services['instanweb.module.nhbusinesscentral.businesscentralconfiguration.config.data.handler'] = new \PrestaShop\PrestaShop\Core\Form\Handler(($this->services['form.factory'] ?? $this->load('getForm_FactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['instanweb.module.nhbusinesscentral.businesscentralconfiguration.config.data'] ?? $this->load('getInstanweb_Module_Nhbusinesscentral_Businesscentralconfiguration_Config_DataService.php')), 'InstanWeb\\Module\\NHBusinessCentral\\Form\\Type\\BusinessCentralConfiguration', 'BusinessCentralConfiguration');
