<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'instanweb.module.nhbusinesscentral.businesscentralconfiguration.config.data' shared service.

return $this->services['instanweb.module.nhbusinesscentral.businesscentralconfiguration.config.data'] = new \InstanWeb\Module\NHBusinessCentral\Provider\ConfigurationData(($this->services['InstanWeb\\Module\\NHBusinessCentral\\Adapter\\Config\\BusinessCentralConfiguration'] ?? $this->load('getBusinessCentralConfigurationService.php')));
