<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'InstanWeb\Module\NHBusinessCentral\Query\TransactionGridQueryBuilder' shared service.

return $this->services['InstanWeb\\Module\\NHBusinessCentral\\Query\\TransactionGridQueryBuilder'] = new \InstanWeb\Module\NHBusinessCentral\Query\TransactionGridQueryBuilder(($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'ps_', ($this->services['prestashop.core.query.doctrine_search_criteria_applicator'] ?? ($this->services['prestashop.core.query.doctrine_search_criteria_applicator'] = new \PrestaShop\PrestaShop\Core\Grid\Query\DoctrineSearchCriteriaApplicator())));
