<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'InstanWeb\Module\NHBusinessCentral\Adapter\Config\BusinessCentralConfiguration' shared service.

return $this->services['InstanWeb\\Module\\NHBusinessCentral\\Adapter\\Config\\BusinessCentralConfiguration'] = new \InstanWeb\Module\NHBusinessCentral\Adapter\Config\BusinessCentralConfiguration(($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] ?? ($this->services['PrestaShop\\PrestaShop\\Adapter\\Configuration'] = new \PrestaShop\PrestaShop\Adapter\Configuration())));
