<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'instanweb.module.nhbusinesscentral.transaction.order.communication' shared service.

return $this->services['instanweb.module.nhbusinesscentral.transaction.order.communication'] = new \InstanWeb\Module\NHBusinessCentral\Transaction\Order\OrderCommunication(($this->services['instanweb.module.nhbusinesscentral.businesscentralconfiguration.config.data'] ?? $this->load('getInstanweb_Module_Nhbusinesscentral_Businesscentralconfiguration_Config_DataService.php')));
