<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'instanweb.module.nhbusinesscentral.transaction.order' shared service.

return $this->services['instanweb.module.nhbusinesscentral.transaction.order'] = new \InstanWeb\Module\NHBusinessCentral\Transaction\Order\Order(($this->services['instanweb.module.nhbusinesscentral.transaction.repository'] ?? $this->load('getInstanweb_Module_Nhbusinesscentral_Transaction_RepositoryService.php')), ($this->services['instanweb.module.nhbusinesscentral.transaction.order.communication'] ?? $this->load('getInstanweb_Module_Nhbusinesscentral_Transaction_Order_CommunicationService.php')));
