<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'instanweb.module.nhbusinesscentral.transactiondetail.grid.factory' shared service.

return $this->services['instanweb.module.nhbusinesscentral.transactiondetail.grid.factory'] = new \PrestaShop\PrestaShop\Core\Grid\GridFactory(($this->services['InstanWeb\\Module\\NHBusinessCentral\\Factory\\TransactionDetailGridDefinitionFactory'] ?? $this->load('getTransactionDetailGridDefinitionFactoryService.php')), ($this->services['instanweb.module.nhbusinesscentral.transactiondetail.grid.data.factory'] ?? $this->load('getInstanweb_Module_Nhbusinesscentral_Transactiondetail_Grid_Data_FactoryService.php')), ($this->services['prestashop.core.grid.filter.form_factory'] ?? $this->load('getPrestashop_Core_Grid_Filter_FormFactoryService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));
