<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'InstanWeb\Module\NHBusinessCentral\Factory\TransactionGridDefinitionFactory' shared service.

$this->services['InstanWeb\\Module\\NHBusinessCentral\\Factory\\TransactionGridDefinitionFactory'] = $instance = new \InstanWeb\Module\NHBusinessCentral\Factory\TransactionGridDefinitionFactory(($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()));

$instance->setTranslator(($this->services['translator'] ?? $this->getTranslatorService()));

return $instance;
