<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoT9dbv\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoT9dbv/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXoT9dbv.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXoT9dbv\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXoT9dbv\appAppKernelProdContainer([
    'container.build_hash' => 'XoT9dbv',
    'container.build_id' => '7dd1d357',
    'container.build_time' => 1737983992,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoT9dbv');
