<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'instanweb.module.nhbusinesscentral.transaction.grid.data.factory' shared service.

return $this->services['instanweb.module.nhbusinesscentral.transaction.grid.data.factory'] = new \PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory(($this->services['InstanWeb\\Module\\NHBusinessCentral\\Query\\TransactionGridQueryBuilder'] ?? $this->load('getTransactionGridQueryBuilderService.php')), ($this->services['PrestaShop\\PrestaShop\\Core\\Hook\\HookDispatcher'] ?? $this->getHookDispatcherService()), ($this->services['prestashop.core.grid.query.doctrine_query_parser'] ?? ($this->services['prestashop.core.grid.query.doctrine_query_parser'] = new \PrestaShop\PrestaShop\Core\Grid\Query\DoctrineQueryParser())), 'TransactionGridDefinitionFactory::GRID_ID');
