<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuxUd2B3sT0+JNUEdcHF5'."\n".'BSxHTff5QMyBAzj1iN74OnycyGnG/xprPj4r4gl7DFAmPWgRtZHwDd0+E0hzLH8x'."\n".'0DFl3awtky9INGfeFblSKZDDPXoHRM0Ih/teslKkGajoHpSN7UFS1h9G+CZsosIw'."\n".'m0jGJ+fV9pl8+BuYSgPn5e0tduu/Se7OWJJ6Htw/f+6pkG8f6E7rsqAFYqQokxRN'."\n".'bbg/LQgrPHWIznuQ+xSP/R/PaBKWAPvxY6HQFqBaRG9muGrDgtix6H/Ht/NcZtdi'."\n".'oxGubpCBBlTwa9RzyPmBOx0Ffb9/UOp4EjeEoh2fknxE1dvybo7saMwpshzkfq19'."\n".'FQIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
