services:
  # Repository
    instanweb.module.nhbusinesscentral.transaction.repository:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Repository\TransactionRepository
        arguments:
          - '@doctrine.dbal.default_connection'
          - '%database_prefix%'

  # Transaction Grid
    InstanWeb\Module\NHBusinessCentral\Controller\TransactionGridController:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Controller\TransactionGridController

    InstanWeb\Module\NHBusinessCentral\Factory\TransactionGridDefinitionFactory:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Factory\TransactionGridDefinitionFactory
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

    InstanWeb\Module\NHBusinessCentral\Query\TransactionGridQueryBuilder:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Query\TransactionGridQueryBuilder
        parent: 'prestashop.core.grid.abstract_query_builder'
        arguments:
          - '@prestashop.core.query.doctrine_search_criteria_applicator'

    instanweb.module.nhbusinesscentral.transaction.grid.data.factory:
        public: true
        class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
        arguments:
          - '@InstanWeb\Module\NHBusinessCentral\Query\TransactionGridQueryBuilder'
          - '@prestashop.core.hook.dispatcher'
          - '@prestashop.core.grid.query.doctrine_query_parser'
          - TransactionGridDefinitionFactory::GRID_ID

    instanweb.module.nhbusinesscentral.transaction.grid.factory:
        public: true
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
          - '@InstanWeb\Module\NHBusinessCentral\Factory\TransactionGridDefinitionFactory'
          - '@instanweb.module.nhbusinesscentral.transaction.grid.data.factory'
          - '@prestashop.core.grid.filter.form_factory'
          - '@prestashop.core.hook.dispatcher'

  # Transaction Detail Grid
    InstanWeb\Module\NHBusinessCentral\Controller\TransactionDetailGridController:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Controller\TransactionDetailGridController

    InstanWeb\Module\NHBusinessCentral\Factory\TransactionDetailGridDefinitionFactory:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Factory\TransactionDetailGridDefinitionFactory
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'

    InstanWeb\Module\NHBusinessCentral\Query\TransactionDetailGridQueryBuilder:
        public: true
        class: InstanWeb\Module\NHBusinessCentral\Query\TransactionDetailGridQueryBuilder
        parent: 'prestashop.core.grid.abstract_query_builder'
        arguments:
          - '@prestashop.core.query.doctrine_search_criteria_applicator'
          - '@request_stack'

    instanweb.module.nhbusinesscentral.transactiondetail.grid.data.factory:
        public: true
        class: 'PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory'
        arguments:
          - '@InstanWeb\Module\NHBusinessCentral\Query\TransactionDetailGridQueryBuilder'
          - '@prestashop.core.hook.dispatcher'
          - '@prestashop.core.grid.query.doctrine_query_parser'
          - TransactionDetailGridDefinitionFactory::GRID_ID

    instanweb.module.nhbusinesscentral.transactiondetail.grid.factory:
        public: true
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        arguments:
          - '@InstanWeb\Module\NHBusinessCentral\Factory\TransactionDetailGridDefinitionFactory'
          - '@instanweb.module.nhbusinesscentral.transactiondetail.grid.data.factory'
          - '@prestashop.core.grid.filter.form_factory'
          - '@prestashop.core.hook.dispatcher'
