<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHUjN8bk\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHUjN8bk/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHUjN8bk.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHUjN8bk\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerHUjN8bk\appAppKernelDevDebugContainer([
    'container.build_hash' => 'HUjN8bk',
    'container.build_id' => '957cd338',
    'container.build_time' => 1738147907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHUjN8bk');
