<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDpB5h1W\appAppKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDpB5h1W/appAppKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDpB5h1W.legacy');

    return;
}

if (!\class_exists(appAppKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDpB5h1W\appAppKernelDevDebugContainer::class, appAppKernelDevDebugContainer::class, false);
}

return new \ContainerDpB5h1W\appAppKernelDevDebugContainer([
    'container.build_hash' => 'DpB5h1W',
    'container.build_id' => 'f5b999a7',
    'container.build_time' => 1734626528,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDpB5h1W');
